### ISSUE TITLE
Example DLL source code

### ISSUE THREAD

**Issue by nm156** [Pugnator/openvsm#2]
Great works!  Would it be possible to include the source code for the example DLLs (Addr.dll, Dbg.dll and k573.dll)?   This would be helpful to see how all the parts all fit together.

**Comment by Pugnator** [comment]
Thanks for your question!
Of course I will. At the moment I'm working under bug fixes and Python bindings

**Comment by Pugnator** [comment]
Can we close this question?

**Comment by nm156** [comment]
Yes, thank you.  The different file sizes of the DLLs is what threw me off.  I understand now that they all all the same file just renamed with a matching script.
