### ISSUE TITLE
Migration to Lua 5.3 failed

### ISSUE THREAD

**Issue by Pugnator** [Pugnator/openvsm#22]
Lua 5.3 provides new functions, like bitwise and number conversion which are custom implemented at the moment. And it greatly degrade performance. Also new Lua represent numbers as 64 bits by default.
Many old functions used by openvsm are now obsolete and need to be replaced. Compilation also fails.

**Comment by nm156** [comment]
This might be a little late, but have you considered using duktape for the language?  http://duktape.org/index.html  It is ECMA scripting (javascript).  I starting some test cases with it trying to avoid the Lua pitfalls.  One of the nice features is duk_peval_file that checks for syntax errors before executing.  The API is very Lua-like. (stack based).  The downside is that javascript is not as friendly as Lua for beginners writing VSM scripts.

**Comment by Pugnator** [comment]
Thanks a lot! Never seen it before.
But I think, first of all, at least Lua based version should be established. When it (and corresponding C part) will be OK, it will be possible to create new bindings for Python, JS and whatever.
At the moment you are the second and only one who left the opinion. So I'm not sure if it really need to be done. There is not so many retro PC enthusiast or discrete logic users (I don't see what else can DIY models be used for), and such a people usually are retrogrades :)
I use it myself and at the moment it is reasonable to use Lua as is... May be I'm wrong about it

**Comment by Pugnator** [comment]
By the way, I tested OpenVSM performance:
The original version on clocking one pin at 100kHz issued 80% CPU Load on my PC.
Now clocking the 8bit bus at 1MHz leads to 60% CPU load on the same PC but Proteus fails to simulate it in realtime after a half a second.
At 100kHz it is 33% of load
