### ISSUE TITLE
dbg.dll.lua example script

### ISSUE THREAD

**Issue by nm156** [Pugnator/openvsm#3]
The code in the repository for example dbg.dll.lua, function device_simulate()  is empty:

function device_simulate()   

end

It should be:

function device_simulate()          
    for i = 0, 7 do        
        if 1 == get_pin_bool(_G["D"..i]) then            
            DATA_BUS = set_bit(DATA_BUS, i)
        else            
            DATA_BUS = clear_bit(DATA_BUS, i)
        end
    end 
    uart_send(string.format("[%d] Fetched opcode %.2X\r\n", systime(), DATA_BUS))   
end

With that change (found by google-fu) everything is working great.  Very impressed with the project!!

**Comment by Pugnator** [comment]
May  I expect pull request from you?

**Comment by nm156** [comment]
Pull request submitted. Closing this issue.
