### ISSUE TITLE
Proteus VSM SDK Copyright Infrigement

### ISSUE THREAD

**Issue by labcenter** [Pugnator/openvsm#38]
Hello,

Please be aware that you have no rights to distribute VSM SDK header files, especially under GPL licence.

Please remove this project, otherwise we will have to contact GitHub administration to take your account down under DMCA infringement policy:

https://help.github.com/articles/dmca-takedown-policy/

Best regards

**Comment by moonglow** [comment]
Hello @labcenter ,
That repository does not distribute original VSM SDK files or code. How you can license just names ? I think some names from your VSM SDK was gotten from other projects too ;) IMHO

**Comment by Pugnator** [comment]
@labcenter I've removed vsm.h and vdm.h, I've added them by mistake (forgot to add them to .gitignore)
