### ISSUE TITLE
Problem with compiling functioning DLL

### ISSUE THREAD

**Issue by nm156** [Pugnator/openvsm#6]
Can you tell me what platform and gcc version were used to build the files in the example directory?
All 3 are different sizes even after stripping, indicating some source code change, 

Files in github
-rwxr-xr-x    1 nm156      Administ   235549 Dec  2 13:44 addr.dll
-rwxr-xr-x    1 nm156      Administ  2301614 Dec  2 13:44 dbg.dll
-rwxr-xr-x    1 nm156      Administ  2300892 Dec  2 13:44 k573.dll

After debug strip
-rwxr-xr-x    1 nm156      Administ   235549 Feb 11 18:59 addr.dll
-rwxr-xr-x    1 nm156      Administ   237070 Feb 11 18:59 dbg.dll
-rwxr-xr-x    1 nm156      Administ   236558 Feb 11 18:59 k573.dll

I tried to compile the github sources on two platforms, both compile
cleanly but neither work properly.  (No outputs from dbg or k573)

I used:
Linux:   gcc-mingw32-4.4.2
-rwxr-xr-x 1 nm156 nm156  237597 2015-02-11 18:17 openvsm.dll

Windows (mingw) : gcc-4.8.1 
-rwxr-xr-x 1 nm156 Administrators 251406 Feb 11 18:38 openvsm.dll

Each of the versions I built seem to ignore get_pin_bool()

I used my DLL for dbg.dll only and if I change the dbg.dll.lua to this:

function device_simulate()          
    for i = 0, 7 do
        if 15 == get_pin_state(_G["D"..i]) then 
        -- if 1 == get_pin_bool(_G["D"..i]) then
            DATA_BUS = set_bit(DATA_BUS, i)
        else            
            DATA_BUS = clear_bit(DATA_BUS, i)
        end
    end 

    text = string.format("[%d] Fetched opcode %.2X\r\n", systime(), DATA_BUS)
    out_log(text)
    uart_send(text)
    
end

I can see the fetched opcode correctly, otherwise DATA_BUS is always 0

With the provided DLLs everything works fine.

**Comment by nm156** [comment]
I can't pretend to know what is going on here but I temporarily solved the problem.

I used a fresh source copy of Lua5.3, built the library and got the same result.

So I dug into lua_bind.c and took a look at lua_get_pin_bool().

Some debugging revealed that the variable 'state' was correct,
lua_pushnumber ( L,  state) but I would never see the value popped from that stack.

There was a similiar issue with lua_set_pin_bool with lua_to_boolean 

So I added

#define lua_pushboolean  lua_pushnumber
#define lua_toboolean lua_tonumber

to the top of lua_bind.c after the include and lo and behold, a nasty hack but it works.
 
Something wonky going on with the boolean stuff in lua.

All 3 example DLLs are now the same DLL using this hack and they all work.

This is just a work around for now.  I'll try and find the root cause.

PS Built with Windows (mingw) : gcc-4.8.1 resultant DLL is 260,622 bytes

**Comment by Pugnator** [comment]
I will test it today and notify about results.
According to example DLLs, they were built in different time during development, so they are differ in size.

**Comment by Pugnator** [comment]
There were bugs with get_pin_bool(), will doublecheck

**Comment by Pugnator** [comment]
As it came out, nothing wrong with Lua but with the script.
One shouldn't use 1 or 0 twith bool types in Lua, but true or false.
But still UART emulator works bad, but it seems to be another issue. Working on it
